import{a as x,S as q,i as d}from"./assets/vendor-DQvd0HNi.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();x.create({baseURL:"https://pixabay.com/api/"});async function m(e,r){throw new Error("Pixabay API key is missing.")}const h=document.querySelector(".gallery"),p=document.querySelector(".loader"),b=document.querySelector(".load-more"),E=new q(".gallery a",{captionsData:"alt",captionDelay:250});function _(e){const r=e.map(B).join("");h.insertAdjacentHTML("beforeend",r),E.refresh()}function g(){h.innerHTML=""}function L(){p.classList.add("is-visible")}function f(){p.classList.remove("is-visible")}function w(){b.classList.add("is-visible")}function s(){b.classList.remove("is-visible")}function B({webformatURL:e,largeImageURL:r,tags:a,likes:l,views:t,comments:o,downloads:n}){return`<li class="gallery__item">
    <a class="gallery__link" href="${r}">
      <img
        class="gallery__image"
        src="${e}"
        alt="${a}"
        loading="lazy"
      />
    </a>
    <div class="gallery__info">
      <p class="gallery__info-item"><span class="gallery__info-label">Likes</span>${l}</p>
      <p class="gallery__info-item"><span class="gallery__info-label">Views</span>${t}</p>
      <p class="gallery__info-item"><span class="gallery__info-label">Comments</span>${o}</p>
      <p class="gallery__info-item"><span class="gallery__info-label">Downloads</span>${n}</p>
    </div>
  </li>`}const y={form:document.querySelector(".form"),loadMoreButton:document.querySelector(".load-more"),gallery:document.querySelector(".gallery")},A=15;let c="",i=1,u=0;f();s();y.form.addEventListener("submit",T);y.loadMoreButton.addEventListener("click",$);async function T(e){e.preventDefault();const r=e.currentTarget.elements["search-text"].value.trim();if(!r){g(),s(),S("Please fill in the search field.");return}c=r,i=1,u=0,g(),s(),L();try{const a=await m(c,i);if(a.hits.length===0){I("Sorry, there are no images matching your search query. Please try again!");return}u=Math.ceil(a.totalHits/A),_(a.hits),P()}catch(a){M(v(a))}finally{f()}}async function $(){i+=1,s(),L();try{const e=await m(c,i);_(e.hits),C(),P()}catch(e){i-=1,M(v(e)),w()}finally{f()}}function P(){if(i>=u){s(),S("We're sorry, but you've reached the end of search results.");return}w()}function C(){const e=y.gallery.firstElementChild;if(!e)return;const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}function v(e){return e.message==="Pixabay API key is missing."?"Add your Pixabay API key to the Vite environment variables to enable search.":"Something went wrong. Please try again later."}function S(e){d.info({message:e,position:"topRight",maxWidth:360})}function I(e){d.warning({message:e,position:"topRight",maxWidth:360})}function M(e){d.error({message:e,position:"topRight",maxWidth:360})}
//# sourceMappingURL=index.js.map
